import { Board, BoardTheme, CardItem, ColumnList } from '../types';
import { DEFAULT_SHEET_GID, DEFAULT_SHEET_ID, DEFAULT_SHEET_URL } from './googleSheets';

export const BOARD_THEMES: BoardTheme[] = [
  {
    id: 'professional-polish',
    name: 'Professional Polish',
    gradient: 'bg-[#F1F2F4]',
    cardBg: 'bg-white',
    headerBg: 'bg-[#0055CC] text-white',
    isDark: false,
  },
  {
    id: 'ocean',
    name: 'Ocean Breeze',
    gradient: 'from-blue-600 via-indigo-700 to-slate-900',
    cardBg: 'bg-white/95 dark:bg-slate-900/90',
    headerBg: 'bg-blue-900/40 backdrop-blur-md border-b border-white/10 text-white',
    isDark: true,
  },
  {
    id: 'slate',
    name: 'Minimalist Clean',
    gradient: 'from-slate-100 to-zinc-200 dark:from-slate-900 dark:to-zinc-950',
    cardBg: 'bg-white dark:bg-slate-800',
    headerBg: 'bg-white/80 dark:bg-slate-900/80 backdrop-blur-md border-b border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white',
    isDark: false,
  },
  {
    id: 'emerald',
    name: 'Forest Canopy',
    gradient: 'from-emerald-700 via-teal-800 to-zinc-900',
    cardBg: 'bg-white/95 dark:bg-zinc-900/90',
    headerBg: 'bg-emerald-950/40 backdrop-blur-md border-b border-white/10 text-white',
    isDark: true,
  },
  {
    id: 'sunset',
    name: 'Sunset Glow',
    gradient: 'from-rose-600 via-orange-600 to-amber-800',
    cardBg: 'bg-white/95 dark:bg-zinc-900/90',
    headerBg: 'bg-rose-950/40 backdrop-blur-md border-b border-white/10 text-white',
    isDark: true,
  },
  {
    id: 'aurora',
    name: 'Northern Aurora',
    gradient: 'from-violet-900 via-purple-900 to-indigo-950',
    cardBg: 'bg-white/95 dark:bg-slate-900/90',
    headerBg: 'bg-purple-950/40 backdrop-blur-md border-b border-white/10 text-white',
    isDark: true,
  },
];

export const INITIAL_LISTS: ColumnList[] = [
  { id: 'list-backlog', title: 'Backlog 📋', order: 0, wipLimit: 10 },
  { id: 'list-todo', title: 'To Do 🎯', order: 1, wipLimit: 6 },
  { id: 'list-in-progress', title: 'In Progress ⚡', order: 2, wipLimit: 4 },
  { id: 'list-review', title: 'In Review 🔍', order: 3, wipLimit: 3 },
  { id: 'list-done', title: 'Done 🎉', order: 4 },
];

export const INITIAL_CARDS: CardItem[] = [
  {
    id: 'card-1',
    title: 'Q3 Global Product Launch & Growth Campaign',
    description: 'Implement multi-channel acquisition campaign, influencer outreach, Google Ads retargeting, and conversion analytics.',
    listId: 'list-in-progress',
    order: 0,
    priority: 'urgent',
    startDate: '2026-08-10',
    etaDate: '2026-08-25',
    dueDate: '2026-08-25',
    completed: false,
    coverColor: '#3b82f6',
    labels: [
      { id: 'lbl-sec', name: 'Growth', color: '#ef4444', bg: 'bg-rose-100 dark:bg-rose-950/60', text: 'text-rose-700 dark:text-rose-300' },
      { id: 'lbl-be', name: 'Marketing', color: '#6366f1', bg: 'bg-indigo-100 dark:bg-indigo-950/60', text: 'text-indigo-700 dark:text-indigo-300' },
    ],
    creator: { id: 'usr-1', name: 'Alex Rivera', email: 'alex@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    assignees: [
      { id: 'usr-1', name: 'Alex Rivera', email: 'alex@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
      { id: 'usr-2', name: 'Sara Lin', email: 'sara@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara' },
    ],
    checklist: [],
    comments: [
      {
        id: 'comm-1',
        authorName: 'Alex Rivera',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        text: 'Campaign assets reviewed. WhatsApp broadcast scheduled for launch day.',
        createdAt: '2026-08-18T14:30:00Z',
      },
    ],
    attachments: [
      {
        id: 'att-1',
        name: 'Campaign_Strategy_Deck.pdf',
        url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600',
        type: 'application/pdf',
        size: '1.4 MB',
        createdAt: '2026-08-18T10:00:00Z',
      },
    ],
    customFields: {
      'Story Points': '8',
      'Sprint': 'Sprint 24',
      'Cost Center': 'Marketing-Q3',
    },
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'card-2',
    title: 'Black Friday & Cyber Week Promotional Blitz',
    description: 'Design dynamic landing pages, email drip sequences, WhatsApp flash deal alerts, and social creative packs.',
    listId: 'list-in-progress',
    order: 1,
    priority: 'high',
    startDate: '2026-08-12',
    etaDate: '2026-08-28',
    dueDate: '2026-08-28',
    completed: false,
    coverColor: '#8b5cf6',
    labels: [
      { id: 'lbl-ui', name: 'Creative', color: '#8b5cf6', bg: 'bg-purple-100 dark:bg-purple-950/60', text: 'text-purple-700 dark:text-purple-300' },
      { id: 'lbl-fe', name: 'Social', color: '#0ea5e9', bg: 'bg-sky-100 dark:bg-sky-950/60', text: 'text-sky-700 dark:text-sky-300' },
    ],
    creator: { id: 'usr-3', name: 'Elena Rostova', email: 'elena@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena' },
    assignees: [
      { id: 'usr-3', name: 'Elena Rostova', email: 'elena@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena' },
    ],
    checklist: [],
    comments: [],
    attachments: [],
    customFields: {
      'Story Points': '5',
      'Sprint': 'Sprint 24',
    },
    createdAt: '2026-08-16T11:20:00Z',
    updatedAt: '2026-08-18T16:00:00Z',
  },
  {
    id: 'card-3',
    title: 'Google Sheets & WhatsApp Live 2-Way Sync Engine',
    description: 'Integrate Google Sheets REST API and WhatsApp live notifications to synchronize status updates with real-time ETA tracking.',
    listId: 'list-review',
    order: 0,
    priority: 'high',
    startDate: '2026-08-15',
    etaDate: '2026-08-22',
    dueDate: '2026-08-22',
    completed: false,
    coverColor: '#10b981',
    labels: [
      { id: 'lbl-sync', name: 'Integration', color: '#10b981', bg: 'bg-emerald-100 dark:bg-emerald-950/60', text: 'text-emerald-700 dark:text-emerald-300' },
      { id: 'lbl-fe', name: 'Automation', color: '#0ea5e9', bg: 'bg-sky-100 dark:bg-sky-950/60', text: 'text-sky-700 dark:text-sky-300' },
    ],
    creator: { id: 'usr-2', name: 'Sara Lin', email: 'sara@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara' },
    assignees: [
      { id: 'usr-1', name: 'Alex Rivera', email: 'alex@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    ],
    checklist: [],
    comments: [
      {
        id: 'comm-2',
        authorName: 'Sara Lin',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
        text: 'Live sync payload verified. Cell coordinate mappings match expected header positions.',
        createdAt: '2026-08-18T17:15:00Z',
      },
    ],
    attachments: [],
    customFields: {
      'Story Points': '13',
      'Sprint': 'Sprint 24',
    },
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-08-18T17:15:00Z',
  },
  {
    id: 'card-4',
    title: 'Customer Retention & VIP Loyalty Re-engagement',
    description: 'Launch personalized WhatsApp customer loyalty incentives with exclusive voucher codes and early access perks.',
    listId: 'list-todo',
    order: 0,
    priority: 'medium',
    startDate: '2026-08-18',
    etaDate: '2026-08-30',
    dueDate: '2026-08-30',
    completed: false,
    labels: [
      { id: 'lbl-fe', name: 'Retention', color: '#0ea5e9', bg: 'bg-sky-100 dark:bg-sky-950/60', text: 'text-sky-700 dark:text-sky-300' },
      { id: 'lbl-feat', name: 'Feature', color: '#f59e0b', bg: 'bg-amber-100 dark:bg-amber-950/60', text: 'text-amber-700 dark:text-amber-300' },
    ],
    creator: { id: 'usr-1', name: 'Alex Rivera', email: 'alex@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    assignees: [
      { id: 'usr-2', name: 'Sara Lin', email: 'sara@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara' },
    ],
    checklist: [],
    comments: [],
    attachments: [],
    customFields: {
      'Story Points': '5',
      'Sprint': 'Sprint 25',
    },
    createdAt: '2026-08-17T08:30:00Z',
    updatedAt: '2026-08-17T08:30:00Z',
  },
  {
    id: 'card-5',
    title: 'Influencer Collab & Media Outreach Campaign',
    description: 'Coordinate product seeding and sponsor agreements across top tech and lifestyle creators with tracked discount links.',
    listId: 'list-todo',
    order: 1,
    priority: 'low',
    startDate: '2026-08-20',
    etaDate: '2026-09-05',
    dueDate: '2026-09-05',
    completed: false,
    labels: [
      { id: 'lbl-feat', name: 'Influencers', color: '#f59e0b', bg: 'bg-amber-100 dark:bg-amber-950/60', text: 'text-amber-700 dark:text-amber-300' },
    ],
    creator: { id: 'usr-3', name: 'Elena Rostova', email: 'elena@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena' },
    assignees: [
      { id: 'usr-3', name: 'Elena Rostova', email: 'elena@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena' },
    ],
    checklist: [],
    comments: [],
    attachments: [],
    customFields: {
      'Story Points': '3',
      'Sprint': 'Sprint 25',
    },
    createdAt: '2026-08-17T11:00:00Z',
    updatedAt: '2026-08-17T11:00:00Z',
  },
  {
    id: 'card-6',
    title: 'Brand Identity & Visual Style Guide Refresh',
    description: 'Standardized typography, logo usage, color palette, and social asset guidelines across all regional marketing materials.',
    listId: 'list-done',
    order: 0,
    priority: 'high',
    startDate: '2026-08-01',
    etaDate: '2026-08-17',
    dueDate: '2026-08-17',
    completed: true,
    coverColor: '#10b981',
    labels: [
      { id: 'lbl-doc', name: 'Branding', color: '#14b8a6', bg: 'bg-teal-100 dark:bg-teal-950/60', text: 'text-teal-700 dark:text-teal-300' },
    ],
    creator: { id: 'usr-1', name: 'Alex Rivera', email: 'alex@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    assignees: [
      { id: 'usr-1', name: 'Alex Rivera', email: 'alex@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
      { id: 'usr-3', name: 'Elena Rostova', email: 'elena@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena' },
    ],
    checklist: [],
    comments: [],
    attachments: [],
    customFields: {
      'Story Points': '3',
      'Sprint': 'Sprint 24',
    },
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-08-17T18:00:00Z',
  },
  {
    id: 'card-7',
    title: 'Holiday Season Referral & Affiliate Program',
    description: 'Setup double-sided referral incentives, affiliate payout tiers, and real-time dashboard analytics.',
    listId: 'list-backlog',
    order: 0,
    priority: 'medium',
    startDate: '2026-09-01',
    etaDate: '2026-09-20',
    dueDate: '2026-09-20',
    completed: false,
    labels: [
      { id: 'lbl-fe', name: 'Affiliates', color: '#0ea5e9', bg: 'bg-sky-100 dark:bg-sky-950/60', text: 'text-sky-700 dark:text-sky-300' },
    ],
    creator: { id: 'usr-2', name: 'Sara Lin', email: 'sara@company.com', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara' },
    assignees: [],
    checklist: [],
    comments: [],
    attachments: [],
    customFields: {
      'Story Points': '5',
      'Sprint': 'Sprint 26',
    },
    createdAt: '2026-08-18T09:00:00Z',
    updatedAt: '2026-08-18T09:00:00Z',
  },
];

export const INITIAL_HEADERS = [
  'Campaign',
  'Status',
  'Description',
  'Priority',
  'Start Date',
  'ETA Date',
  'Assignee',
  'Labels',
  'Story Points',
  'Sprint',
  'Cost Center',
];

export const INITIAL_BOARD: Board = {
  id: 'board-main',
  title: 'Campaign & Project Operations Board',
  description: 'Connected to Google Sheet: https://docs.google.com/spreadsheets/d/1GYOXTCW5NLDvaIh4elVRRthln2orBY8sryqQect3kfE/edit?gid=265307111',
  spreadsheetId: DEFAULT_SHEET_ID,
  spreadsheetGid: DEFAULT_SHEET_GID,
  spreadsheetUrl: DEFAULT_SHEET_URL,
  sheetTabName: 'Sheet1',
  availableTabs: ['Sheet1', 'Campaign Roadmap', 'Archived Campaigns'],
  lists: INITIAL_LISTS,
  cards: INITIAL_CARDS,
  headers: INITIAL_HEADERS,
  columnMapping: {
    titleCol: 'Campaign',
    listCol: 'Status',
    descCol: 'Description',
    priorityCol: 'Priority',
    startDateCol: 'Start Date',
    etaDateCol: 'ETA Date',
    dueDateCol: 'ETA Date',
    assigneeCol: 'Assignee',
    labelsCol: 'Labels',
    customCols: ['Story Points', 'Sprint', 'Cost Center'],
  },
  lastSyncedAt: new Date().toISOString(),
  autoSync: true,
  theme: BOARD_THEMES[0],
};
